package com.algobuddy.gui;

import java.awt.Component;
import java.awt.Container;
import java.awt.Rectangle;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/**
 *
 * @author nebir, nazrul
 */
public class JSlidingPanel extends javax.swing.JPanel {

    public enum Direction {
        Left,
        Right,
        up,
        Down
    };

    /**
     * Creates new form JSlidingPanel
     */
    public JSlidingPanel() {
        initComponents();
    }

    void nextSlidingPanel(int panelSpeed, Component hiddenPanel, Direction direction) {
        Component currentComp = getCurrentComponent(this);
        hiddenPanel.setVisible(true);
        JSlidingPanelListener listener = new JSlidingPanelListener(panelSpeed, currentComp, hiddenPanel, direction);
        Timer t = new Timer(40, listener);
        listener.timer = t;
        t.start();
        refresh();
    }

    public Component getCurrentComponent(Container parent) {
        Component comp = null;
        int n = parent.getComponentCount();
        for (int i = 0; i < n; i++) {
            comp = parent.getComponent(i);
            if (comp.isVisible()) {
                return comp;
            }
        }
        return comp;
    }

    public class JSlidingPanelListener implements ActionListener {

        Component visiblePanel;
        Component hiddenPanel;
        int steps;
        int step = 0;
        Timer timer;
        Direction direction;

        public JSlidingPanelListener(int steps, Component visiblePanel, Component hiddenPanel, Direction direction) {
            this.steps = steps;
            this.visiblePanel = visiblePanel;
            this.hiddenPanel = hiddenPanel;
            this.direction = direction;
        }

        @Override
        public void actionPerformed(ActionEvent e) {

            Rectangle bounds = visiblePanel.getBounds();
            int shift = bounds.width / steps;
            int shiftUp = bounds.height / steps;
            switch (direction) {
                case Left:
                    visiblePanel.setLocation(bounds.x - shift, bounds.y);
                    hiddenPanel.setLocation(bounds.x - shift + bounds.width, bounds.y);
                    break;
                case Right:
                    visiblePanel.setLocation(bounds.x + shift, bounds.y);
                    hiddenPanel.setLocation(bounds.x + shift - bounds.width, bounds.y);
                    break;

                case up:
                    visiblePanel.setLocation(bounds.x, bounds.y - shiftUp);
                    hiddenPanel.setLocation(bounds.x, bounds.y - shiftUp + bounds.height);
                    break;
                case Down:
                    visiblePanel.setLocation(bounds.x, bounds.y + shiftUp);
                    hiddenPanel.setLocation(bounds.x, bounds.y + shiftUp - bounds.height);
                    break;
            }

            repaint();
            step++;

            if (step == steps) {
                timer.stop();
                visiblePanel.setVisible(false);
            }
        }
    }

    public void refresh() {
        revalidate();
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setPreferredSize(new java.awt.Dimension(800, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
